# Site settings

title: ADA class 2019 : Where do your purchases rank in our analysis ?
tag_text: Purchases ranking
description: ADA project of team gobigorgohome
url: "127.0.0.1:4000"
baseurl: "https://marckbickel.github.io/project_gobigorgohome"
font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
